=== markbrito/vxd/vxd3/vxd/Translators/Translator.dtd
<!ELEMENT Translator (toolbar?,menu?,eventhandler)>
<!ATTLIST Translator Name CDATA #IMPLIED
                     TranslatorXSL CDATA #IMPLIED>
<!ELEMENT toolbar (toolbarbutton+)>
<!ELEMENT toolbarbutton (#PCDATA)>
<!ATTLIST toolbarbutton image CDATA #IMPLIED
                        text CDATA #IMPLIED 
			command CDATA #IMPLIED>
<!ELEMENT menu (menuitem+)>
<!ATTLIST menu name CDATA #IMPLIED
               letter CDATA #IMPLIED>
<!ELEMENT menuitem (#PCDATA)>
<!ATTLIST menuitem image CDATA #IMPLIED
                   text CDATA #IMPLIED
		   command CDATA #IMPLIED>
<!ELEMENT eventhandler (#PCDATA)>
<!ATTLIST eventhandler class CDATA #IMPLIED>

=== markbrito/vxd/vxd3/vxd/Translators/VisualAltaBPM/VisualAltaBPM.xml
<?xml version="1.0"?>
<!DOCTYPE Translator SYSTEM "../Translator.dtd">
<Translator name="VisualAltaBPM" 
            TranslatorXSL="VisualAltaBPM.xsl">
<toolbar>
   <toolbarbutton image="Translators/VisualAltaBPM/Images/savecode.gif" text="Save Generated Code" command="SAVECODE"/>
   <toolbarbutton image="Translators/VisualAltaBPM/Images/savexsl.gif" text="Save XSL" command="SAVEXSL"/>
</toolbar>
<menu name="XSL" letter="S">
   <menuitem image="Translators/VisualAltaBPM/Images/savecode.gif" text="Save Generated Code" command="SAVECODE"/>
   <menuitem image="Translators/VisualAltaBPM/Images/savexsl.gif" text="Save XSL" command="SAVEXSL"/>
</menu>
<eventhandler class="vxd.Translators.VisualHTMLtoHTML.ExternalTranslators.TranslationActionEventHandler"/>
</Translator>

=== markbrito/vxd/vxd3/vxd/Translators/VisualHTMLtoHTML/VisualHTMLtoHTML.xml
<?xml version="1.0"?>
<!DOCTYPE Translator SYSTEM "../Translator.dtd">
<Translator name="VisualHTMLtoHTML" 
            TranslatorXSL="VisualHTMLtoHTML.xsl">
<toolbar>
   <toolbarbutton image="Translators/VisualHTMLtoHTML/Images/savecode.gif" text="Save Generated Code" command="SAVECODE"/>
   <toolbarbutton image="Translators/VisualHTMLtoHTML/Images/savexsl.gif" text="Save XSL" command="SAVEXSL"/>
</toolbar>
<menu name="XSL" letter="S">
   <menuitem image="Translators/VisualHTMLtoHTML/Images/savecode.gif" text="Save Generated Code" command="SAVECODE"/>
   <menuitem image="Translators/VisualHTMLtoHTML/Images/savexsl.gif" text="Save XSL" command="SAVEXSL"/>
</menu>
<eventhandler class="vxd.Translators.VisualHTMLtoHTML.ExternalTranslators.TranslationActionEventHandler"/>
</Translator>

=== markbrito/vxd/vxd3/vxd/Translators/VisualWebJavaServlet/VisualWebJavaServlet.xml
<?xml version="1.0"?>
<!DOCTYPE Translator SYSTEM "../Translator.dtd">
<Translator name="VisualWebJavaServlet" 
            TranslatorXSL="VisualWebJavaServlet.xsl">
<toolbar>
   <toolbarbutton image="Translators/VisualWebJavaServlet/Images/savecode.gif" text="Save Generated Code" command="SAVECODE"/>
   <toolbarbutton image="Translators/VisualWebJavaServlet/Images/savexsl.gif" text="Save XSL" command="SAVEXSL"/>
</toolbar>
<menu name="XSL" letter="S">
   <menuitem image="Translators/VisualWebJavaServlet/Images/savecode.gif" text="Save Generated Code" command="SAVECODE"/>
   <menuitem image="Translators/VisualWebJavaServlet/Images/savexsl.gif" text="Save XSL" command="SAVEXSL"/>
</menu>
<eventhandler class="vxd.Translators.VisualWebJavaServlet.ExternalTranslators.TranslationActionEventHandler"/>
</Translator>

=== markbrito/vxd/vxd3/vxd/Translators/VisualDTDtoDTD/VisualDTDtoDTD.xml
<?xml version="1.0"?>
<!DOCTYPE Translator SYSTEM "../Translator.dtd">
<Translator name="VisualDTDtoDTD" 
            TranslatorXSL="VisualDTDtoDTD.xsl">
<toolbar>
   <toolbarbutton image="Translators/VisualDTDtoDTD/Images/savecode.gif" text="Save Generated Code" command="SAVECODE"/>
   <toolbarbutton image="Translators/VisualDTDtoDTD/Images/savexsl.gif" text="Save XSL" command="SAVEXSL"/>
</toolbar>
<menu name="XSL" letter="S">
   <menuitem image="Translators/VisualDTDtoDTD/Images/savecode.gif" text="Save Generated Code" command="SAVECODE"/>
   <menuitem image="Translators/VisualDTDtoDTD/Images/savexsl.gif" text="Save XSL" command="SAVEXSL"/>
</menu>
<eventhandler class="vxd.Translators.VisualDTDtoDTD.ExternalTranslators.TranslationActionEventHandler"/>
</Translator>

=== markbrito/vxd/vxd1/vxd/Translators/ASPNETCSharpASPX/ASPNETCSharpASPX.xml
<?xml version="1.0"?>
<!DOCTYPE Translator SYSTEM "../Translator.dtd">
<Translator name="ASPNETCSharpASPX" 
            TranslatorXSL="ASPNETCSharpASPX.xsl">
<toolbar>
   <toolbarbutton image="Translators/ASPNETCSharpASPX/Images/savecode.gif" text="Save Generated Code" command="SAVECODE"/>
   <toolbarbutton image="Translators/ASPNETCSharpASPX/Images/savexsl.gif" text="Save XSL" command="SAVEXSL"/>
</toolbar>
<menu name="XSL" letter="S">
   <menuitem image="Translators/ASPNETCSharpASPX/Images/savecode.gif" text="Save Generated Code" command="SAVECODE"/>
   <menuitem image="Translators/ASPNETCSharpASPX/Images/savexsl.gif" text="Save XSL" command="SAVEXSL"/>
</menu>
<eventhandler class="vxd.Translators.ASPNETCSharpASPX.ExternalTranslators.TranslationActionEventHandler"/>
</Translator>
