=== markbrito/vxd/vxd3/vxd/Languages/Language.dtd
<!ELEMENT Language (Icons,Connectors,Editors?)>
<!ATTLIST Language Name CDATA #IMPLIED
                   StructureDTD CDATA #IMPLIED>
<!ELEMENT Icons (Icon)*>
<!ELEMENT Icon (#PCDATA)>
<!ATTLIST Icon Name CDATA #IMPLIED
               Image CDATA #IMPLIED>
<!ELEMENT Connectors (Connector)*>
<!ELEMENT Connector (#PCDATA)>
<!ATTLIST Connector Name CDATA #IMPLIED
                    Image CDATA #IMPLIED
                    Type (AGGREGATION|CONNECTION) "CONNECTION">
<!ELEMENT Editors (Editor)*>
<!ELEMENT Editor (#PCDATA)>
<!ATTLIST Editor Name CDATA #REQUIRED
                 Class CDATA #REQUIRED
		 ElementName CDATA #REQUIRED
		 AttributeName CDATA #REQUIRED
		 Type (DIALOG|PANEL) "DIALOG">

=== markbrito/vxd/vxd3/vxd/Languages/DTD/DTD.xml
<?xml version="1.0"?>
<!DOCTYPE Language SYSTEM "../Language.dtd">
<Language Name="DTD" StructureDTD="DTD.dtd">
 <Icons>
   <Icon Name="ELEMNTGROUP" Image="Languages/DTD/Images/ELEMNTGROUP.gif"/>
   <Icon Name="ELEMNT" Image="Languages/DTD/Images/ELEMNT.gif"/>
   <Icon Name="ATTLST" Image="Languages/DTD/Images/ATTLST.gif"/>
   <Icon Name="ATT" Image="Languages/DTD/Images/ATT.gif"/>
   <Icon Name="ATTITEM" Image="Languages/DTD/Images/ATTITEM.gif"/>
 </Icons>
 <Connectors>
   <Connector Name="Connection" Image="Languages/DTD/Images/connection.gif" Type="CONNECTION"/>
<!--   <Connector Name="MapAttribute" Image="Languages/DTD/Images/connection.gif" Type="CONNECTION"/>
   <Connector Name="MapAttributeList" Image="Languages/DTD/Images/connections.gif" Type="CONNECTION"/>
   <Connector Name="MapElement" Image="Languages/DTD/Images/connection.gif" Type="CONNECTION"/>
 -->
 </Connectors>
 <Editors>
   <Editor Name="VariableSelector" 
           Class="vxd.Languages.VisualWeb.Editors.VariableSelector" 
	   ElementName="ELEMNTGROUP" AttributeName="Variable" Type="PANEL"/>
   <Editor Name="VariableSelector" 
           Class="vxd.Languages.VisualWeb.Editors.VariableSelector" 
	   ElementName="ELEMNT" AttributeName="Variable" Type="PANEL"/>
   <Editor Name="VariableSelector" 
           Class="vxd.Languages.VisualWeb.Editors.VariableSelector" 
	   ElementName="ATTLST" AttributeName="Variable" Type="PANEL"/>
   <Editor Name="VariableSelector" 
           Class="vxd.Languages.VisualWeb.Editors.VariableSelector" 
	   ElementName="ATT" AttributeName="Variable" Type="PANEL"/>
   <Editor Name="VariableSelector" 
           Class="vxd.Languages.VisualWeb.Editors.VariableSelector" 
	   ElementName="ATTITEM" AttributeName="Variable" Type="PANEL"/>
 </Editors>
</Language>
